spring:
  application:
    name: FullStack
  cache:
    cache-names: ehcache
    ehcache:
      config: ehcache.xml
  mvc:
    static-path-pattern: /resources/**
  freemarker:
    cache: true
    charset: utf-8
    enabled: true
    view-names: index,error
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
        fixed:
          enabled: true
          paths: /js/lib
          version: v12
  datasource:
    url: jdbc:mysql://localhost:3306/jBlog
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


server:
  port: 8080
  max-http-header-size: 8192
  compression:
      min-response-size: 512
      enabled: true
      mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
  tomcat:
        maxThreads: 10
        minSpareThreads: 3
        accesslog:
          directory: /home/fullstack/app/log/server_log
          pattern: combined
          enabled: true


security:
  user:
    password: weak


logging:
    config: classpath:log4j2.xml


