spring:
  application:
    name: FullStack
  cache:
    cache-names: ehcache
    ehcache:
      config: ehcache.xml
  thymeleaf:
    cache: false
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: true
    charset: utf-8
    enabled: true
    view-names: index,error
    template-loader-path: classpath:/templates/
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**
        fixed:
          enabled: true
          paths: /js/lib
          version: v12
    static-locations: classpath:/static/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/public/
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/jcala_blog?useUnicode:true&amp;characterEncoding:UTF-8
    driverClassName: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 50
      minimum-idle: 5


server:
  port: 8080
  max-http-header-size: 8192
  compression:
      min-response-size: 512
      enabled: true
      mime-types: text/html,text/css,text/javascript,application/javascript,image/gif,image/png,image/jpg
  tomcat:
        maxThreads: 12
        minSpareThreads: 3
        accesslog:
          directory: /home/fullstack/app/log/server_log
          pattern: combined
          enabled: true

logging:
    config: classpath:log4j2.xml
mybatis:
  type-aliases-package: me.zbl.fullstack.mapper
  type-handlers-package: org.apache.ibatis.type.LocalDateTypeHandler
  config-location: classpath:mybatis-config.xml
